spring.application.name=dpd
spring.thymeleaf.cache=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

server.port=8080

# Configurações de Sessão
server.servlet.session.timeout=30m

                        ## DevTools ##
# Recomendação: Desativar DevTools em produção, pois reinicia o servidor se houver alterações no disco.
# Isso causa falhas no carregamento de CSS/JS (o servidor vai abaixo momentaneamente).
# spring.devtools.restart.enabled=true
# spring.devtools.livereload.enabled=true
# spring.thymeleaf.cache=false
# spring.devtools.restart.additional-paths=src/main/java,src/main/resources

# Configuração de Cache para ficheiros estáticos (CSS, JS, Imagens)
spring.web.resources.cache.cachecontrol.max-age=7d
spring.web.resources.cache.cachecontrol.cache-public=true

# Controle de Logs (INFO = Ligado, OFF = Desligado completo)
logging.level.co.ao.base=INFO
logging.level.root=INFO

                        ## API CONFIG ##
api.key=${API_KEY:a0b136527367da54a4b8}
api.base-url=${API_BASE_URL:https://api-parceiros.dexa-contas.com/api/v1}

# Jackson: desabilitar timestamps, activar módulo de Java Time
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false
